name = "grove-gemini"
description = "Tools for Google's Gemini API"
type = "go"
managed = true

[binary]
name = "grove-gemini"
path = "./bin/grove-gemini"

[context]
default_rules_path = ".cx/dev-no-tests.rules"
